@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic as LogicPackage {

' Group all CommandParser subclasses
package ParserClasses {
class CommandParserSubclasses as "CommandParser subclasses\n(AddPerson, AddPet, etc.)"
}

' Group all Command subclasses
class CommandSubclasses as "Command subclasses\n(Add, Delete, Edit, Find, List, etc.)"

class CommandResult
class "{abstract}\nCommand" as Command
class "<<interface>>\nLogic" as Logic
class LogicManager
}

package Model {
class Model MODEL_COLOR
}

package Storage {
class Storage STORAGE_COLOR
}

' Key relationships
LogicManager ..|> Logic
LogicManager --> ParserClasses
ParserClasses ..> CommandSubclasses : <<create>>
CommandSubclasses --|> Command
LogicManager --> Model
LogicManager --> Storage
Logic ..> CommandResult
LogicManager ..> CommandResult
Command ..> CommandResult : <<create>>
LogicManager ..> Command : <<call>>
Command ..> Model

@enduml
