@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4

package Logic as LogicPackage {
Class "<<interface>>\nLogic" as Logic LOGIC_COLOR
Class LogicManager LOGIC_COLOR
}

package Model as ModelPackage {
Class "<<interface>>\nModel" as Model MODEL_COLOR
Class ModelManager MODEL_COLOR
}

package Storage as StoragePackage {
Class "<<interface>>\nStorage" as Storage STORAGE_COLOR
Class StorageManager STORAGE_COLOR
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

LogicManager .up.|> Logic
ModelManager .up[MODEL_COLOR].|> Model
StorageManager .up[STORAGE_COLOR].|> Storage

LogicManager --> Model
LogicManager --> Storage
@enduml
